package io.github.azukkia.pairdesk.core.crypto

import io.github.azukkia.pairdesk.core.PairDeskDefaults
import io.github.azukkia.pairdesk.core.TestFiles
import io.github.azukkia.pairdesk.core.bytes
import io.github.azukkia.pairdesk.core.json.JsonJs
import io.github.azukkia.pairdesk.core.obj
import io.github.azukkia.pairdesk.core.text
import io.github.azukkia.pairdesk.core.transport.MqttTransport
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.long
import org.junit.jupiter.api.Assertions.assertArrayEquals
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.DynamicTest
import org.junit.jupiter.api.DynamicTest.dynamicTest
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.TestFactory

/**
 * Checks every step of the protocol against the vectors produced by the
 * JavaScript implementation of the desktop app (android/protocol-vectors.json,
 * generated by scripts/protocol-vectors.mjs).
 */
class ProtocolVectorsTest {
    private val cases = TestFiles.vectorList("cpace")

    private fun forEachCase(name: String, check: (JsonObject) -> Unit): List<DynamicTest> =
        cases.map { c -> dynamicTest("$name [${c.text("sid")}]") { check(c) } }

    private fun hex(b: ByteArray) = Hex.encode(b)

    @Test
    fun `vectors are present`() {
        assertEquals(2, cases.size)
        assertEquals(3, TestFiles.vectorList("hashToRistretto").size)
        assertEquals(2, TestFiles.vectorList("mqttTopics").size)
    }

    @TestFactory
    fun prs() = forEachCase("PRS = PBKDF2-HMAC-SHA256(NFC(trim(password)), host id)") { c ->
        assertEquals(c.text("prs"), hex(Prs.derive(c.text("password"), c.text("hostId"))))
    }

    @TestFactory
    fun channelIdentifier() = forEachCase("CI") { c ->
        assertEquals(c.text("ci"), hex(CPace.channelIdentifier(c.text("ctrlId"), c.text("hostId"))))
    }

    @TestFactory
    fun generator() = forEachCase("generator input and point") { c ->
        val prs = c.bytes("prs")
        val ci = c.bytes("ci")
        assertEquals(c.text("generatorInput"), hex(CPace.generatorInput(prs, ci, c.text("sid"))))
        assertEquals(c.text("generator"), hex(CPace.generator(prs, ci, c.text("sid")).compress().toByteArray()))
    }

    @TestFactory
    fun shares() = forEachCase("shares from the given scalars") { c ->
        val a = CPace.scalarFromHexBigEndian(c.text("scalarA"))
        val b = CPace.scalarFromHexBigEndian(c.text("scalarB"))
        val ya = CPace.shareWithScalar(c.bytes("prs"), c.bytes("ci"), c.text("sid"), a)
        val yb = CPace.shareWithScalar(c.bytes("prs"), c.bytes("ci"), c.text("sid"), b)
        assertEquals(c.text("ya"), hex(ya.share))
        assertEquals(c.text("yb"), hex(yb.share))
        assertEquals(c.text("yaB64u"), B64u.encode(ya.share))
        assertArrayEquals(ya.share, B64u.decode(c.text("yaB64u")))
    }

    @TestFactory
    fun sharedSecret() = forEachCase("K on both sides") { c ->
        val a = CPace.scalarFromHexBigEndian(c.text("scalarA"))
        val b = CPace.scalarFromHexBigEndian(c.text("scalarB"))
        assertEquals(c.text("k"), hex(CPace.secret(a, c.bytes("yb"))))
        assertEquals(c.text("k"), hex(CPace.secret(b, c.bytes("ya"))))
    }

    @TestFactory
    fun keySchedule() = forEachCase("transcript and the four keys") { c ->
        val keys = CPace.deriveSessionKeys(c.text("sid"), c.text("ctrlId"), c.text("hostId"), c.bytes("ya"), c.bytes("yb"), c.bytes("k"))
        assertEquals(c.text("transcript"), hex(keys.transcript))
        assertEquals(c.text("tagKeyHost"), hex(keys.tagKeyHost))
        assertEquals(c.text("tagKeyCtrl"), hex(keys.tagKeyCtrl))
        assertEquals(c.text("encHostToCtrl"), hex(keys.encHostToCtrl))
        assertEquals(c.text("encCtrlToHost"), hex(keys.encCtrlToHost))
    }

    @TestFactory
    fun confirmationTags() = forEachCase("host and controller tags") { c ->
        val keys = CPace.deriveSessionKeys(c.text("sid"), c.text("ctrlId"), c.text("hostId"), c.bytes("ya"), c.bytes("yb"), c.bytes("k"))
        assertEquals(c.text("hostTag"), hex(CPace.hostTag(keys)))
        assertEquals(c.text("ctrlTag"), hex(CPace.ctrlTag(keys)))
        assertTrue(constantTimeEquals(c.bytes("hostTag"), CPace.hostTag(keys)))
    }

    @TestFactory
    fun sealedMessages() = forEachCase("open the sealed intro / accepted and reseal them") { c ->
        val sid = c.text("sid")
        val keys = CPace.deriveSessionKeys(sid, c.text("ctrlId"), c.text("hostId"), c.bytes("ya"), c.bytes("yb"), c.bytes("k"))
        val intro = c.obj("sealedIntro")
        val accepted = c.obj("sealedAccepted")

        // Host opens the controller's intro, controller opens the host's accepted.
        val openedIntro = SecureChannel.forHost(keys, sid).open(intro)
        assertEquals(JsonJs.parse(intro.text("plaintext")), openedIntro)
        val openedAccepted = SecureChannel.forController(keys, sid).open(accepted)
        assertEquals(JsonJs.parse(accepted.text("plaintext")), openedAccepted)

        // Sealing the same plaintext with the same counter gives the same bytes.
        val resealedIntro = SecureChannel.forController(keys, sid).seal(JsonJs.parse(intro.text("plaintext")))
        assertEquals(intro["n"]!!.jsonPrimitive.long, resealedIntro.n)
        assertEquals(intro.text("ct"), resealedIntro.ct)
        val resealedAccepted = SecureChannel.forHost(keys, sid).seal(JsonJs.parse(accepted.text("plaintext")))
        assertEquals(accepted["n"]!!.jsonPrimitive.long, resealedAccepted.n)
        assertEquals(accepted.text("ct"), resealedAccepted.ct)
        // JSON.stringify and our serializer agree byte for byte on these messages.
        assertEquals(intro.text("plaintext"), JsonJs.stringify(openedIntro))
    }

    @TestFactory
    fun hashToRistretto(): List<DynamicTest> = TestFiles.vectorList("hashToRistretto").map { v ->
        dynamicTest("hash_to_ristretto255(\"${v.text("msg")}\")") {
            val point = HashToRistretto.hashToRistretto255(v.text("msg").toByteArray(Charsets.UTF_8), v.text("dst"))
            assertEquals(v.text("point"), hex(point.compress().toByteArray()))
        }
    }

    @Test
    fun `DST is the one of the desktop`() {
        TestFiles.vectorList("hashToRistretto").forEach { assertEquals(CPace.DST, it.text("dst")) }
    }

    @TestFactory
    fun mqttTopics(): List<DynamicTest> = TestFiles.vectorList("mqttTopics").map { v ->
        dynamicTest("topic of ${v.text("id")}") {
            assertEquals(v.text("topic"), MqttTransport.topicFor(PairDeskDefaults.MQTT_TOPIC_PREFIX, v.text("id")))
        }
    }
}
